### ISSUE TITLE
addBootstrapClasses() shouldn't includes the class 'form-control'

### ISSUE THREAD

**Issue by mandrew** [unclecheese/silverstripe-bootstrap-forms#25]
Just looking though the Bootstrap documentation and this class should only be added on form fields, not checkboxes and buttons etc. Any reason why the addBootstrapClasses() function adds this class everywhere?

http://getbootstrap.com/css/#forms-control-sizes

**Comment by mandrew** [comment]
@unclecheese bump ; )

**Comment by bbstuntman** [comment]
@mandrew any news about bootstrap fields? I'm trying to recode the admin panel but I'm stuck on fields set :-(

**Comment by mandrew** [comment]
@bbstuntman try using the latest master (dev-master in composer) as @unclecheese has created a patch for this class issue

**Comment by bbstuntman** [comment]
@mandrew Thanks. I will give it a check tomorrow. I am trying to recode / rewrite the admin dashboard, based on the AdminLTE 2.3, but by now i'm a little bit stuck with the GridFields and Forms, I don't know how to recode them.. :-( I'm new to SilverStripe, and I'm new as programmer ( never done before ). It's hard the first time to understand a lot of stuff( it's 1 month on SS Framework ), but I think SS is one of the most easy and consolidated ORM framework out there. Thanks a lot again. 

btw here is job not ended... :-)
![screen shot 2015-10-20 at 17 18 16](https://cloud.githubusercontent.com/assets/4539062/10649191/f1975a3e-7842-11e5-843a-b3a408c7a1c1.png)

**Comment by unclecheese** [comment]
As far as I can tell, this method `addBootstrapClasses()` no longer exists. Closing.
