### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by digi-brains** [unclecheese/silverstripe-bootstrap-forms#46]
Is this not installable with composer?

`The requested package unclecheese/silverstripe-bootstrap-forms could not be found in any version, there may be a typo in the package name.`

**Comment by unclecheese** [comment]
I think you want this `unclecheese/bootstrap-forms`.

See the `"replaces": ` node in the `composer.json` file. It's packagist's completely unreliable way reconciling old package names.

**Comment by digi-brains** [comment]
Ah, yes. That certainly makes more sense. Thank you, sir.
